;; 增加IO性能
;; (setq read-process-output-max (* 10240 1024))
;; (setq process-adaptive-read-buffering nil)
(setq gc-cons-threshold most-positive-fixnum)
(require 'cl-lib)

(tool-bar-mode -1)
(menu-bar-mode -1)
(scroll-bar-mode -1)

(add-to-list 'load-path "~/.emacs.d/site-lisp/pkg/themes")
(add-to-list 'load-path "~/.emacs.d/site-lisp/pkg/ef-themes")
(add-to-list 'load-path "~/.emacs.d/site-lisp/pkg/dash.el")
(require 'dash)
(require 'doom-themes)
;; (require 'ef-themes)
;; (load-theme 'ef-night t t)
(load-theme 'doom-one t t)
;; (load-theme 'doom-one-light t t)
;; (load-theme 'modus-vivendi t t)
;; (load-theme 'ef-dark t t)
