(require 's)
(require 'f)
(require 'elisp-refs)
(require 'helpful)
(require 'elisp-demos)
(define-key global-map [remap describe-function] 'helpful-function)
(define-key global-map [remap describe-key] 'helpful-key)
(define-key global-map [remap describe-variable] 'helpful-variable)
(define-key global-map [remap describe-command] 'helpful-command)
(advice-add 'helpful-update :after #'elisp-demos-advice-helpful-update)
(provide 'init-helpful)
